# Generated by Django 5.1.4 on 2024-12-09 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_email', models.CharField(max_length=50)),
                ('p_phone', models.CharField(max_length=50)),
                ('p_department', models.CharField(max_length=50)),
                ('p_date', models.DateField()),
                ('p_msh', models.TextField(max_length=500)),
                ('p_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
            ],
        ),
    ]
